# -*- coding: utf-8 -*-
"""GenAI EXP 5B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTHAREGADWqinS8KqtZAujCAFW5GCOYm
"""

!pip install pypdf sentence-transformers faiss-cpu numpy transformers

!pip install --upgrade transformers

from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
from transformers import pipeline
from typing import List
from textwrap import wrap as word_wrap

def load_pdf(path: str) -> str:
    reader = PdfReader(path)
    full_text = ""
    for page in reader.pages:
        full_text += page.extract_text() or ""
    return full_text


def chunk_text(text: str,
               chunk_size: int = 500,
               overlap: int = 50) -> List[str]:

    words  = text.split()
    chunks = []
    start  = 0

    while start < len(words):
        end   = start + chunk_size
        chunk = " ".join(words[start:end])
        chunks.append(chunk)
        start += chunk_size - overlap

    return chunks

def build_embeddings(chunks: List[str],
                     model_name: str = "all-MiniLM-L6-v2"):

    print(f"  Loading embedding model: {model_name} ...")
    embedder = SentenceTransformer(model_name)

    print(f"  Embedding {len(chunks)} chunks ...")
    embeddings = embedder.encode(chunks, show_progress_bar=True)

    return embedder, embeddings.astype("float32")

def build_faiss_index(embeddings: np.ndarray) -> faiss.Index:
    dimension = embeddings.shape[1]

    index = faiss.IndexFlatL2(dimension)

    index.add(embeddings)
    print(f"  FAISS index built: {index.ntotal} vectors stored.")

    return index

def retrieve(query: str,
             embedder,
             index: faiss.Index,
             chunks: List[str],
             top_k: int = 3) -> List[str]:

    query_vec = embedder.encode([query]).astype("float32")

    distances, indices = index.search(query_vec, top_k)

    retrieved = [chunks[idx] for idx in indices[0] if idx != -1]
    return retrieved

def generate_answer(query: str,
                    context_chunks: List[str],
                    generator,
                    max_tokens: int = 300) -> str:

    context = "\n\n---\n\n".join(context_chunks)

    prompt = f"""Answer the question using only the context below.
If the answer is not in the context, say
"I don't know based on the provided documents."

Context:
{context}

Question: {query}

Answer:"""

    result = generator(prompt, max_new_tokens=max_tokens)
    return result[0]["generated_text"].strip()

def build_rag_pipeline(pdf_paths: List[str]):
    all_chunks = []
    for pdf_path in pdf_paths:
        print(f"\n[+] Loading: {pdf_path}")
        text   = load_pdf(pdf_path)
        chunks = chunk_text(text, chunk_size=500, overlap=50)
        print(f"    -> {len(chunks)} chunks extracted")
        all_chunks.extend(chunks)

    print(f"\n[+] Total chunks: {len(all_chunks)}")

    print("\n[+] Building embeddings ...")
    embedder, embeddings = build_embeddings(all_chunks)

    print("\n[+] Building FAISS index ...")
    index = build_faiss_index(embeddings)

    return embedder, index, all_chunks


def ask(query: str, embedder, index, chunks, generator, top_k: int = 3):
    print(f"\n{'='*60}")
    print(f"QUESTION: {query}")
    print(f"{'='*60}")

    print("\n[Retrieve] Searching FAISS index ...")
    context = retrieve(query, embedder, index, chunks, top_k=top_k)
    print(f"  -> {len(context)} chunks retrieved")

    print("\n[Generate] Calling flan-t5-base ...")
    answer = generate_answer(query, context, generator)

    print("\nANSWER:\n")
    for line in word_wrap(answer, width=70):
        print(" ", line)
    return answer

PDF_FILES = [
    "5b_pdf.pdf",
    "5b_pdf2.pdf",
]

embedder, index, chunks = build_rag_pipeline(PDF_FILES)

print("\n[+] Loading local LLM: flan-t5-base ...")
generator = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

questions = [
    "What is the core idea behind the attention mechanism?",
    "How does BERT differ from traditional language models?",
    "What datasets were used for pre-training?",
]

for q in questions:
    ask(q, embedder, index, chunks, generator)