# -*- coding: utf-8 -*-
"""GenAI EXP 5A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgSgv8L2Ou40O1W1Y2tfrahbWVmF0ssI
"""

!pip install langchain langchain-community langchain-text-splitters langchain-huggingface faiss-cpu sentence-transformers

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

file_path = "sample.txt"
loader = TextLoader(file_path, encoding="utf-8")
documents = loader.load()
print(f"Loaded {len(documents)} document(s)")

splitter = CharacterTextSplitter(
    separator="\n",
    chunk_size=500,
    chunk_overlap=50
)

split_docs = splitter.split_documents(documents)
print(f"Total chunks created: {len(split_docs)}")

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = FAISS.from_documents(
    documents=split_docs,
    embedding=embeddings
)

query = "What is this document about?"
results = vectorstore.similarity_search(query, k=3)

for i, doc in enumerate(results, start=1):
    print(f"\nResult {i}")
    print("-" * 50)
    print(doc.page_content)
    print("Metadata:", doc.metadata)